create table if not exists public.lost_found_items (
    id bigint generated by default as identity primary key,
    type text not null check (type in ('lost', 'found')),
    title text not null,
    description text not null default '',
    location text not null,
    status text not null default 'active' check (status in ('active', 'resolved')),
    created_at timestamptz not null default now()
);

create index if not exists lost_found_items_created_at_idx
    on public.lost_found_items (created_at desc);

alter table public.lost_found_items enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'lost_found_items'
          and policyname = 'Allow anonymous lost and found reads'
    ) then
        create policy "Allow anonymous lost and found reads"
            on public.lost_found_items for select
            to anon using (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'lost_found_items'
          and policyname = 'Allow anonymous lost and found inserts'
    ) then
        create policy "Allow anonymous lost and found inserts"
            on public.lost_found_items for insert
            to anon with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'lost_found_items'
          and policyname = 'Allow anonymous lost and found updates'
    ) then
        create policy "Allow anonymous lost and found updates"
            on public.lost_found_items for update
            to anon using (true) with check (true);
    end if;
end $$;